#!/bin/bash
#BSUB -n 1
#BSUB -R "span[hosts=1]"

mkdir -p /export/cluster-tmp/chenyehu
export TMPDIR=/export/cluster-tmp/chenyehu

module add seas-lab-vorobeychik

RANK=$1
TYPE=$2
python latent_traits.py -r ${RANK} -t ${TYPE}