#!/bin/bash
#BSUB -n 1
#BSUB -R "span[hosts=1]"

mkdir -p /export/cluster-tmp/chenyehu
export TMPDIR=/export/cluster-tmp/chenyehu

module add seas-lab-vorobeychik

n=$1
m=$2
t=$3
SEED=$4
RANK=$5
TYPE=$6
python python utilities/generate_data.py -n ${n} -m ${m} -t ${t} -s ${SEED} -r ${RANK}
python simulation.py -n ${n} -m ${m} -t ${t} -s ${SEED} -r ${RANK} -k ${TYPE}